# Generated by Django 6.0.5 on 2026-06-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'permissions': [('can_create_event', 'Can create new events')]},
        ),
    ]
